SERVER_PORT : 8002
AUTHENTICATION: http://localhost:9001/authentication
AUTHORIZATION: http://localhost:9001/authorization
MEMBER_URL: http://localhost:8000/api/v1/member

server:
  port: ${SERVER_PORT}
